### ISSUE TITLE
Collectd network plugin requires two puppet runs

### ISSUE THREAD

**Issue by johnf** [puppet-community/puppet-collectd#162]
https://github.com/pdxcat/puppet-module-collectd/blob/master/templates/plugin/network.conf.erb#L3

This depends on collectd_version. The fact is being evaluated at catalog compile time which is before collectd is installed. So it probably ends up as nil, so the SecurityLevel isn't set.

Then on a second run when it detects collectd 5 is installed then it adds the SecurityLevel

Not sure what a good solution to this problem is though. Maybe the fact could work out what version is going to be installed? Something like

```bash
apt-cache madison collectd | grep Packages | head -1 | awk -F\| '{print $2}' | sed -e 's/-.*//'
```

**Comment by ngagecj** [comment]
Any work around about this issue ?

**Comment by bdellegrazie** [comment]
Here is another suggestion:
instead of using the fact directly in the ERB templates, why not use a class variable (e.g. `$_collectd_version`) which is set based on one of the following sources:

* `$version` (if it represents an explicit version - major.minor.revision parts only)
* `$collectd_version` fact, if not undef / nil
* default version supplied from hiera or minimum version supported by this module

This permits the system administrator to use an explicit version for the package and get a single puppet run and/or to supply a default minimum version if these are not set.
e.g. assuming class with defaults as follows (untested)

```puppet
class collectd(
  ...
  $version  = installed,
  $collectd_default_version = '5.0.0',
) inherits collectd::params {
  ...
   $_collectd_version = pick( regsubst($version, '^\d+\.\d+\.\d+', '\0'), $collectd_version, $collectd_default_version)
  ...
}
```
Then use `$_collectd_version` in the ERB templates.

What do you think?

**Comment by bdellegrazie** [comment]
@johnf, @txaj, @jpoittevin, @ngagecj:
Any comment on my potential solution above? I'm happy to create a PR if its considered reasonable.
Thanks

**Comment by txaj** [comment]
This is a great idea!

In your PR you may want 1/ not to break compatibility by setting the $collectd_default_version to undef, so it'll still need two runs if not explicitly configured 2/ document this feature both in the "usage" section and down the README with a format like "Puppet needs two runs to correctly write my conf, why ?" and refer to this issue

**Comment by bdellegrazie** [comment]
@txaj: I've raised the PR as requested.
I've tested this but it relies upon the user loading the collectd class before instantiating any plugin classes. I'm not sure there's a way around this.
Tests for the plugins have been updated but there isn't an easy way of testing the version selector as its only exposed by an internal variable.
Thoughts?

**Comment by bdellegrazie** [comment]
Rebased to current master

**Comment by igalic** [comment]
with the closing of #305 can we close this issue, too?
